// Auto-generated by hedge_core
window.__STATISTICS_DATA__ = {
  "meta": {
    "module": "Statistics",
    "generatedAt": "2026-04-16T07:24:25Z",
    "source": "Elexys scrape + XLS history",
    "asof": "2026-04-14",
    "currency": "EUR",
    "unit": "MWh",
    "ytdStart": "2026-01-01",
    "sessions": [
      {
        "label": "7/4",
        "weekday": "Tuesday",
        "date": "2026-04-07"
      },
      {
        "label": "8/4",
        "weekday": "Wednesday",
        "date": "2026-04-08"
      },
      {
        "label": "9/4",
        "weekday": "Thursday",
        "date": "2026-04-09"
      },
      {
        "label": "10/4",
        "weekday": "Friday",
        "date": "2026-04-10"
      },
      {
        "label": "13/4",
        "weekday": "Monday",
        "date": "2026-04-13"
      },
      {
        "label": "14/4",
        "weekday": "Tuesday",
        "date": "2026-04-14"
      }
    ]
  },
  "markets": [
    {
      "group": "ELECTRICITY",
      "products": [
        {
          "code": "BE_POWER_M1",
          "label": "BE M+1 base",
          "absCode": "BE_POWER|MONTH|2026|05",
          "prices": [
            95.01,
            87.65,
            88.51,
            83.3,
            84.57,
            83.04
          ],
          "varD1": -1.81,
          "varW1": -12.6,
          "avg": 76.76,
          "max": 96.06,
          "min": 60.56
        },
        {
          "code": "BE_POWER_Q1",
          "label": "BE Q+1 base",
          "absCode": "BE_POWER|QTR|2026|3",
          "prices": [
            102.67,
            94.01,
            95.09,
            92.07,
            94.66,
            92.5
          ],
          "varD1": -2.28,
          "varW1": -9.91,
          "avg": 84.17,
          "max": 109.3,
          "min": 67.78
        },
        {
          "code": "BE_POWER_Q2",
          "label": "BE Q+2 base",
          "absCode": "BE_POWER|QTR|2026|4",
          "prices": [
            113.08,
            104.09,
            105.38,
            101.44,
            104.55,
            101.43
          ],
          "varD1": -2.99,
          "varW1": -10.3,
          "avg": 95.38,
          "max": 121.92,
          "min": 80.1
        },
        {
          "code": "BE_POWER_Y1",
          "label": "BE Y+1 base",
          "absCode": "BE_POWER|CAL|2027",
          "prices": [
            92.92,
            86.28,
            87.47,
            84.69,
            86.01,
            84.37
          ],
          "varD1": -1.9,
          "varW1": -9.2,
          "avg": 81.71,
          "max": 95.77,
          "min": 71.86
        },
        {
          "code": "BE_POWER_Y2",
          "label": "BE Y+2 base",
          "absCode": "BE_POWER|CAL|2028",
          "prices": [
            77.84,
            74.88,
            74.78,
            73.56,
            73.88,
            73.63
          ],
          "varD1": -0.34,
          "varW1": -5.41,
          "avg": 73.11,
          "max": 78.74,
          "min": 67.47
        },
        {
          "code": "BE_POWER_Y3",
          "label": "BE Y+3 base",
          "absCode": "BE_POWER|CAL|2029",
          "prices": [
            73.73,
            72.01,
            72.13,
            71.36,
            71.63,
            71.11
          ],
          "varD1": -0.73,
          "varW1": -3.55,
          "avg": 70.69,
          "max": 74.13,
          "min": 66.76
        }
      ]
    },
    {
      "group": "GAS",
      "products": [
        {
          "code": "TTF_M1",
          "label": "TTF M+1",
          "absCode": "TTF|MONTH|2026|05",
          "prices": [
            53.25,
            45.3,
            46.17,
            43.64,
            46.41,
            43.37
          ],
          "varD1": -6.56,
          "varW1": -18.55,
          "avg": 38.62,
          "max": 61.81,
          "min": 26.1
        },
        {
          "code": "TTF_Q1",
          "label": "TTF Q+1",
          "absCode": "TTF|QTR|2026|3",
          "prices": [
            53.14,
            45.43,
            46.26,
            43.52,
            45.85,
            43.02
          ],
          "varD1": -6.17,
          "varW1": -19.04,
          "avg": 37.97,
          "max": 60.89,
          "min": 26.21
        },
        {
          "code": "TTF_Q2",
          "label": "TTF Q+2",
          "absCode": "TTF|QTR|2026|4",
          "prices": [
            52.62,
            45.34,
            46.1,
            43.26,
            45.27,
            42.49
          ],
          "varD1": -6.15,
          "varW1": -19.26,
          "avg": 37.91,
          "max": 60.26,
          "min": 26.73
        },
        {
          "code": "TTF_Y1",
          "label": "TTF Y+1",
          "absCode": "TTF|CAL|2027",
          "prices": [
            41.66,
            37.0,
            37.23,
            35.25,
            36.52,
            34.74
          ],
          "varD1": -4.88,
          "varW1": -16.61,
          "avg": 31.48,
          "max": 46.68,
          "min": 24.74
        },
        {
          "code": "TTF_Y2",
          "label": "TTF Y+2",
          "absCode": "TTF|CAL|2028",
          "prices": [
            29.5,
            27.6,
            27.56,
            26.95,
            27.35,
            26.7
          ],
          "varD1": -2.38,
          "varW1": -9.5,
          "avg": 25.24,
          "max": 32.21,
          "min": 22.71
        },
        {
          "code": "TTF_Y3",
          "label": "TTF Y+3",
          "absCode": "TTF|CAL|2029",
          "prices": [
            25.03,
            24.3,
            24.15,
            23.9,
            24.18,
            23.75
          ],
          "varD1": -1.8,
          "varW1": -5.12,
          "avg": 22.58,
          "max": 25.21,
          "min": 21.03
        }
      ]
    }
  ]
};
