// Auto-generated by hedge_core — do not edit
window.__STATISTICS_DATA__ = {
  "meta": {
    "module": "Statistics",
    "generatedAt": "2026-04-20T18:57:25Z",
    "source": "Elexys daily scrape + XLS history",
    "asof": "2026-04-17",
    "currency": "EUR",
    "unit": "MWh",
    "ytdStart": "2026-01-01",
    "sessions": [
      {
        "label": "10/4",
        "weekday": "Friday",
        "date": "2026-04-10"
      },
      {
        "label": "13/4",
        "weekday": "Monday",
        "date": "2026-04-13"
      },
      {
        "label": "14/4",
        "weekday": "Tuesday",
        "date": "2026-04-14"
      },
      {
        "label": "15/4",
        "weekday": "Wednesday",
        "date": "2026-04-15"
      },
      {
        "label": "16/4",
        "weekday": "Thursday",
        "date": "2026-04-16"
      },
      {
        "label": "17/4",
        "weekday": "Friday",
        "date": "2026-04-17"
      }
    ]
  },
  "markets": [
    {
      "group": "ELECTRICITY",
      "products": [
        {
          "code": "BE_POWER_M1",
          "label": "BE M+1 base",
          "absCode": "BE_POWER|MONTH|2026|05",
          "prices": [
            83.3,
            84.57,
            83.04,
            80.5,
            78.95,
            null
          ],
          "varD1": -1.93,
          "varW1": -10.8,
          "avg": 76.85,
          "max": 96.06,
          "min": 60.56
        },
        {
          "code": "BE_POWER_Q1",
          "label": "BE Q+1 base",
          "absCode": "BE_POWER|QTR|2026|3",
          "prices": [
            92.07,
            94.66,
            92.5,
            89.33,
            85.39,
            null
          ],
          "varD1": -4.41,
          "varW1": -10.2,
          "avg": 84.26,
          "max": 109.3,
          "min": 67.78
        },
        {
          "code": "BE_POWER_Q2",
          "label": "BE Q+2 base",
          "absCode": "BE_POWER|QTR|2026|4",
          "prices": [
            101.44,
            104.55,
            101.43,
            99.41,
            97.98,
            null
          ],
          "varD1": -1.44,
          "varW1": -7.02,
          "avg": 95.47,
          "max": 121.92,
          "min": 80.1
        },
        {
          "code": "BE_POWER_Y1",
          "label": "BE Y+1 base",
          "absCode": "BE_POWER|CAL|2027",
          "prices": [
            84.69,
            86.01,
            84.37,
            83.35,
            82.61,
            null
          ],
          "varD1": -0.89,
          "varW1": -5.56,
          "avg": 81.74,
          "max": 95.77,
          "min": 71.86
        },
        {
          "code": "BE_POWER_Y2",
          "label": "BE Y+2 base",
          "absCode": "BE_POWER|CAL|2028",
          "prices": [
            73.56,
            73.88,
            73.63,
            73.81,
            74.18,
            null
          ],
          "varD1": 0.5,
          "varW1": -0.8,
          "avg": 73.14,
          "max": 78.74,
          "min": 67.47
        },
        {
          "code": "BE_POWER_Y3",
          "label": "BE Y+3 base",
          "absCode": "BE_POWER|CAL|2029",
          "prices": [
            71.36,
            71.63,
            71.11,
            70.94,
            71.13,
            null
          ],
          "varD1": 0.27,
          "varW1": -1.39,
          "avg": 70.7,
          "max": 74.13,
          "min": 66.76
        }
      ]
    },
    {
      "group": "GAS",
      "products": [
        {
          "code": "TTF_M1",
          "label": "TTF M+1",
          "absCode": "TTF|MONTH|2026|05",
          "prices": [
            43.64,
            46.41,
            43.37,
            43.37,
            41.4,
            38.77
          ],
          "varD1": -6.35,
          "varW1": -11.16,
          "avg": 38.73,
          "max": 61.81,
          "min": 26.1
        },
        {
          "code": "TTF_Q1",
          "label": "TTF Q+1",
          "absCode": "TTF|QTR|2026|3",
          "prices": [
            43.52,
            45.85,
            43.02,
            43.02,
            41.31,
            38.84
          ],
          "varD1": -5.98,
          "varW1": -10.75,
          "avg": 38.1,
          "max": 60.89,
          "min": 26.21
        },
        {
          "code": "TTF_Q2",
          "label": "TTF Q+2",
          "absCode": "TTF|QTR|2026|4",
          "prices": [
            43.26,
            45.27,
            42.49,
            42.49,
            40.9,
            38.81
          ],
          "varD1": -5.11,
          "varW1": -10.29,
          "avg": 38.03,
          "max": 60.26,
          "min": 26.73
        },
        {
          "code": "TTF_Y1",
          "label": "TTF Y+1",
          "absCode": "TTF|CAL|2027",
          "prices": [
            35.25,
            36.52,
            34.74,
            34.74,
            34.02,
            33.21
          ],
          "varD1": -2.38,
          "varW1": -5.78,
          "avg": 31.58,
          "max": 46.68,
          "min": 24.74
        },
        {
          "code": "TTF_Y2",
          "label": "TTF Y+2",
          "absCode": "TTF|CAL|2028",
          "prices": [
            26.95,
            27.35,
            26.7,
            26.7,
            26.7,
            26.39
          ],
          "varD1": -1.16,
          "varW1": -2.07,
          "avg": 25.3,
          "max": 32.21,
          "min": 22.71
        },
        {
          "code": "TTF_Y3",
          "label": "TTF Y+3",
          "absCode": "TTF|CAL|2029",
          "prices": [
            23.9,
            24.18,
            23.75,
            23.75,
            23.72,
            23.45
          ],
          "varD1": -1.14,
          "varW1": -1.88,
          "avg": 22.62,
          "max": 25.21,
          "min": 21.03
        }
      ]
    }
  ]
};
